CREATE TABLE IF NOT EXISTS accounts (
    id            BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username      VARCHAR(16)  NOT NULL UNIQUE,
    password_hash CHAR(64)     NOT NULL,
    salt          CHAR(32)     NOT NULL,
    created_at    DATETIME     DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- test accounts (password: "testpass" — replace in production)
-- hash/salt generated by CryptoUtil::HashPassword
INSERT INTO accounts (username, password_hash, salt) VALUES
    ('testuser', '0000000000000000000000000000000000000000000000000000000000000000', '00000000000000000000000000000000');
